import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase/client';

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const periodType = searchParams.get('period_type') || 'week';
  const startDate = searchParams.get('start') || '';
  const endDate = searchParams.get('end') || '';

  try {
    // Fetch metrics for the period
    let query = supabase
      .from('metric_snapshots')
      .select(`
        *,
        flows (
          id,
          name,
          purpose,
          live,
          products (name)
        )
      `)
      .eq('period_type', periodType)
      .order('period_start_date', { ascending: false });

    if (startDate) {
      query = query.gte('period_start_date', startDate);
    }

    if (endDate) {
      query = query.lte('period_start_date', endDate);
    }

    const { data: metrics, error } = await query;

    if (error) throw error;

    // Generate simple HTML for PDF conversion
    // (In production, use a proper PDF library like puppeteer or react-pdf)
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Channel Health Report</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              max-width: 1200px;
              margin: 0 auto;
              padding: 20px;
            }
            h1 {
              color: #1e40af;
              border-bottom: 3px solid #1e40af;
              padding-bottom: 10px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 12px;
              text-align: left;
            }
            th {
              background-color: #f3f4f6;
              font-weight: bold;
            }
            .badge {
              display: inline-block;
              padding: 4px 8px;
              border-radius: 4px;
              font-size: 12px;
              font-weight: bold;
            }
            .badge-green { background: #d1fae5; color: #065f46; }
            .badge-amber { background: #fef3c7; color: #92400e; }
            .badge-red { background: #fee2e2; color: #991b1b; }
            .summary {
              background: #f9fafb;
              padding: 20px;
              border-radius: 8px;
              margin: 20px 0;
            }
            .meta {
              color: #6b7280;
              font-size: 14px;
              margin-bottom: 20px;
            }
          </style>
        </head>
        <body>
          <h1>Channel Health Report</h1>
          <div class="meta">
            <p><strong>Period Type:</strong> ${periodType}</p>
            <p><strong>Date Range:</strong> ${startDate || 'All'} to ${endDate || 'All'}</p>
            <p><strong>Generated:</strong> ${new Date().toISOString().split('T')[0]}</p>
          </div>

          <div class="summary">
            <h2>Executive Summary</h2>
            <p><strong>Total Workflows:</strong> ${metrics?.length || 0}</p>
            <p><strong>Total Sends:</strong> ${metrics?.reduce((sum, m: any) => sum + m.sends, 0).toLocaleString()}</p>
            <p><strong>Average Open Rate:</strong> ${
              metrics?.length
                ? (metrics.reduce((sum, m: any) => sum + (m.open_rate || 0), 0) / metrics.length).toFixed(1)
                : 0
            }%</p>
          </div>

          <h2>Performance Details</h2>
          <table>
            <thead>
              <tr>
                <th>Workflow</th>
                <th>Product</th>
                <th>Channel</th>
                <th>Period</th>
                <th>Sends</th>
                <th>Open Rate</th>
                <th>Click Rate</th>
              </tr>
            </thead>
            <tbody>
              ${(metrics || []).map((m: any) => `
                <tr>
                  <td>${m.flows?.name || m.workflow_id}</td>
                  <td>${m.flows?.products?.name || '-'}</td>
                  <td style="text-transform: capitalize">${m.channel}</td>
                  <td>${m.period_start_date}</td>
                  <td>${m.sends.toLocaleString()}</td>
                  <td>${m.open_rate ? m.open_rate.toFixed(1) + '%' : '-'}</td>
                  <td>${m.click_rate ? m.click_rate.toFixed(1) + '%' : '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #6b7280; font-size: 12px;">
            <p>Generated by CRM Atlas • ${new Date().toLocaleString()}</p>
          </div>
        </body>
      </html>
    `;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="health-report-${periodType}-${new Date().toISOString().split('T')[0]}.html"`,
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}
